server:
  port: 8083


#rabbitmq
spring:
  rabbitmq:
    host: 192.168.50.205
    port: 5671
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 10000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 5
#        retry:
#          max-attempts: 5
#          enabled: true
#          initial-interval: 10000
#        default-requeue-rejected: true


