server:
  max-http-header-size: 8192
  port: 2030

test: "%@!fqfilm2020"

spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    dynamic:
      primary: projectx
      datasource:
        projectx:
          url: jdbc:mysql://123.60.96.93:11006/projectx?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=true
          username: ivas
          password: Ivas.18601121086
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
        ivas:
          url: jdbc:mysql://123.60.96.93:11006/ivas?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=true
          username: ivas
          password: Ivas.18601121086
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.mysql.dao.entity.**
  global-config:
    db-config:
      # 自动生成id规则
      id-type: ID_WORKER_STR
      # 删除后
      logic-delete-value: 1
      # 删除前
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl