server:
  port: 2040

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://192.168.50.72:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

